### ISSUE TITLE
Session Invalidated just after login JWT Authenticator

### ISSUE THREAD

**Issue by VincentMolinie** [fenichelar/ember-simple-auth-token#175] opened 2016-10-25 15:08 UTC
I have an issue with the JWT Authenticator, everytime I try to login it says sessionAuthenticated but immediately after sessionInvalidated is fired... So Ican't log in. The probleme is coming from internal-session sessionDataUpdated where the authenticated object is empty and so it's clearing the session.
Why this sessionDataUpdated is fired ?

**Comment by Ramblurr** [comment] 2017-01-12 13:10
I'm experiencing the same behavior with 2.0.0

**Comment by Ramblurr** [comment] 2017-01-12 13:18
Tracing the cause even further it seems the 'storage' event is being fired and in `local-storage.js`  of ember-simple-auth and it is being cleared.

The event seems to be clearing the session data

```json
key: "ember_simple_auth-session"
newValue: "{"authenticated":{}}"
oldValue: "{"authenticated":{ ... token data... }}"
```

**Comment by VincentMolinie** [comment] 2017-01-12 13:47
I've fixed this issue but I don't remember how, sorry :/

**Comment by amk221** [comment] 2017-01-17 18:00
I'm experiencing this too. For me at least, I think it's something to do with the Ember Data Adapter Mixin and loading the currently authenticated user's information.
When attempting to `findRecord` it doesn't get as far as making the request, and I get logged out.

_Edit_: It seems that ember-simple-auth-token was looking for a factory `authorizer:jwt` but there is no such thing. I changed this in the Adapter to `authorizer:token`, and *now it works*.

**Comment by woosungchu** [comment] 2017-02-14 13:43
I'm experienced this and fix it. This error caused by wrong configuration.

You should specify set authorizer 'token' to adapter but 'jwt' to environment.js  ...

    //app/config/environment.js
      ENV['ember-simple-auth'] = {
        authorizer: 'authorizer:jwt'
      };

and

    //app/adapters/application.js
    import DRFAdapter from './drf';
    import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

    export default DRFAdapter.extend(DataAdapterMixin, {
      namespace: 'api',
      authorizer : 'authorizer:token'
    });

**Comment by amk221** [comment] 2017-02-14 13:57
Any explanation as to why? It doesn't seem right...

**Comment by eluciano11** [comment] 2017-02-14 15:19
@amk221 Yeah, we merged a PR that updated the docs and it said that people should use `authorizer:jwt` but that authorizer never existed in the project. We have `authenticator:jwt` and `authenticator:token` so this was our mistake for not double checking/remembering.

**Comment by amk221** [comment] 2017-02-14 15:21
👌 cool thanks for the clarification

**Comment by eluciano11** [comment] 2017-02-14 15:22
Thank you and sorry for any inconvenience this might have caused you.

**Closed as completed by eluciano11** 2017-02-14 15:22 UTC
