### ISSUE TITLE
Missing Authorization Headers

### ISSUE THREAD

**Issue by nonovd** [fenichelar/ember-simple-auth-token#125] opened 2016-01-31 14:32 UTC
Hello, 
I have an authorization problem. I can authenticate but in the following requests, the authorization headers are never sent. 

> ember: 2.3.0
> ember data: 2.3.0
> ember-simple-auth: "git://github.com/simplabs/ember-simple-auth.git"
> ember-simple-auth-token: 1.0.0

Whitout the authorization headers, request is forbidden as it should and is followed by this error:

> Error while processing route: Adapter operation failed Error: Adapter operation failed
#### adapter/application.js

``` javascript
import DS from "ember-data";
import ENV from 'myapp/config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
    authorizer: 'authorizer:token',
    host: ENV.APP.API_HOST,
    namespace: 'api',

    buildURL: function(type, id, record){
        return this._super(type, id, record) + '/';
    },
    shouldBackgroundReloadRecord: function() {
        return false;
    },
    shouldReloadAll: function() {
        return true;
    },
});
```
#### config/environnement.js

``` javascript
    ENV['ember-simple-auth'] = {
      authorizer: 'authorizer:token',
      routeAfterAuthentication: 'app.home',
    };

    ENV['ember-simple-auth-token'] = {
      serverTokenEndpoint: ENV.APP.API_HOST+'/rest-auth/login/',
      identificationField: 'username',
      passwordField: 'password',
      tokenPropertyName: 'key',
      authorizationPrefix: 'Token ',
      authorizationHeaderName: 'Authorization',
    };
```
#### routes/application.js

``` javascript
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  actions: {
    invalidateSession: function() {
       ...
    }
  }
});
```

I tried to add AuthenticatedRouteMixin to the route I want to access but it does nothing more:

``` javascript
import Ember from "ember";
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin,{
    model: function() {
        return this.store.findAll('measurement');
    }
});
```

Am I missing something ? Thank you

**Comment by dbinetti** [comment] 2016-02-02 18:06
I am having the same issue, using the default implementation

**Comment by dbinetti** [comment] 2016-02-02 20:35
I'm not terribly experienced with Ember, but if I am reading the source code correctly this is not designed to work with Ember Simple Auth 1.0  According to the upgrade docs here: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10
the `authenticate` method requires the `credentials` argument to be decomposed into `identification` and `password`, which is not the case here: ember-simple-auth-token/addon/authenticators/token.js

**Comment by eluciano11** [comment] 2016-02-04 12:28
Duplicate of #96

**Closed as completed by eluciano11** 2016-02-04 12:28 UTC
