### ISSUE TITLE
Silent login after user confirm

### ISSUE THREAD

**Issue by thagul** [fenichelar/ember-simple-auth-token#64] opened 2015-06-09 11:49 UTC
I've a service where user should confirm his account after signup.
Confirmation is made clicking on a link sent via email. Once the user clicks that link, I confirm his account server side and return a token to the client. 
How can I set that token as the authorize token and then silently login the user?
I've tried setting session variables but I wasn't able to 'tell' to simple-auth to use that value as the authorizer token to use in following requests.

**Comment by jpadilla** [comment] 2015-06-10 20:40
@thagul haven't done this before, but I'd suspect that you could probably set `session.secure` to have the same object as you would after login. Closing as this is definitely not a bug and more of a usage question regarding simple auth. Feel free to post your solution here when you do.

**Closed as completed by jpadilla** 2015-06-10 20:40 UTC
